version: 2
updates:
  - package-ecosystem: composer
    directory: /app
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    groups:
      composer-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /landing
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
