version: 2
updates:
  - package-ecosystem: composer
    directory: /app
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    groups:
      composer-security:
        applies-to: security-updates
        patterns:
          - "*"
      composer-all:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    groups:
      docker-root-security:
        applies-to: security-updates
        patterns:
          - "*"
      docker-root-all:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /landing
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    groups:
      docker-landing-security:
        applies-to: security-updates
        patterns:
          - "*"
      docker-landing-all:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    groups:
      actions-security:
        applies-to: security-updates
        patterns:
          - "*"
      actions-all:
        patterns:
          - "*"
