name: Build & Push app + landing

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "release-*" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_BASE: jacob-finance   # <--- your base image name (repo path after your username)

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # --- image 1: app ---
          - name: app
            tag: app
            context: .
            file: ./Dockerfile.app          # adjust if your file is named differently
          # --- image 2: landing ---
          - name: landing
            tag: landing
            context: ./landing              # adjust to the folder you build from
            file: ./landing/Dockerfile      # adjust if needed

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push (${{ matrix.name }})
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_BASE }}:${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
