name: Build & Push app + landing Docker

on:
  #push:
  #  branches: [ "main" ]
  #  tags: [ "v*", "release-*" ]
  workflow_dispatch:    

env:
  IMAGE_BASE: finance   # <--- your base image name (repo path after your username)

permissions: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        include:
          # --- image 1: app ---
          - name: app
            tag: app
            context: .
            file: ./Dockerfile          # adjust if your file is named differently
          # --- image 2: landing ---
          - name: landing
            tag: landing
            context: ./landing              # adjust to the folder you build from
            file: ./landing/Dockerfile      # adjust if needed

    steps:
      - uses: actions/checkout@v6

      #Only needed for multi aritecture builds
      #- uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push (${{ matrix.name }})
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_BASE }}:${{ matrix.tag }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,scope=${{ matrix.name }},mode=max

